// Code generated by "stringer -type TokenType -trimprefix TT_"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TT_EOF-0]
	_ = x[TT_ERROR-1]
	_ = x[TT_LBRACE-2]
	_ = x[TT_RBRACE-3]
	_ = x[TT_LPAREN-4]
	_ = x[TT_RPAREN-5]
	_ = x[TT_COMMA-6]
	_ = x[TT_PLUS-7]
	_ = x[TT_MINUS-8]
	_ = x[TT_STAR-9]
	_ = x[TT_SLASH-10]
	_ = x[TT_IDENT-11]
	_ = x[TT_INT-12]
	_ = x[TT_CHAR-13]
	_ = x[TT_FN-14]
	_ = x[TT_MAIN-15]
	_ = x[TT_DEO-16]
}

const _TokenType_name = "EOFERRORLBRACERBRACELPARENRPARENCOMMAPLUSMINUSSTARSLASHIDENTINTCHARFNMAINDEO"

var _TokenType_index = [...]uint8{0, 3, 8, 14, 20, 26, 32, 37, 41, 46, 50, 55, 60, 63, 67, 69, 73, 76}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
