// Code generated by "stringer -type TokenType -trimprefix TT_"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TT_EOF-0]
	_ = x[TT_ERROR-1]
	_ = x[TT_IDENT-2]
	_ = x[TT_INT-3]
	_ = x[TT_CHAR-4]
	_ = x[TT_LBRACE-5]
	_ = x[TT_COMMA-6]
	_ = x[TT_RBRACE-7]
	_ = x[TT_FN-8]
	_ = x[TT_DEO-9]
}

const _TokenType_name = "EOFERRORIDENTINTCHARLBRACECOMMARBRACEFNDEO"

var _TokenType_index = [...]uint8{0, 3, 8, 13, 16, 20, 26, 31, 37, 39, 42}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
