// Code generated by "stringer -type TokenType -trimprefix TT_"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TT_EOF-0]
	_ = x[TT_IDENT-1]
	_ = x[TT_INT-2]
	_ = x[TT_CHAR-3]
	_ = x[TT_LBRACE-4]
	_ = x[TT_COMMA-5]
	_ = x[TT_RBRACE-6]
	_ = x[TT_FN-7]
	_ = x[TT_DEO-8]
}

const _TokenType_name = "EOFIDENTINTCHARLBRACECOMMARBRACEFNDEO"

var _TokenType_index = [...]uint8{0, 3, 8, 11, 15, 21, 26, 32, 34, 37}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
